// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import "ZGAppType.h"
#import "ZGAppidVersion.h"
#import <Foundation/Foundation.h>
@class ZGAppSupport;
@protocol ZGAutoConfigDelegate;
@protocol ZGRoomListUpdateListener;
@protocol ZGSdkAudioDelegate;
@protocol ZGSdkCommonDelegate;
@protocol ZGSdkVideoDelegate;


@interface ZGAppSupport : NSObject

/** 创建配置api */
+ (nullable ZGAppSupport *)create;

/** 设置自动配置参数 */
- (void)setAutoConfigParams:(ZGAppType)type
                   configId:(nonnull NSString *)configId;

/** 更新配置 */
- (void)updateAppConfig:(nullable id<ZGAutoConfigDelegate>)delegate;

/** 设置房间列表监听 */
- (void)setRoomListUpdateListener:(nullable id<ZGRoomListUpdateListener>)listener;

/** 更新房间列表 */
- (void)updateRoomList:(int64_t)appid;

/** 设置alpha环境 */
- (void)setUseAlphaEnv:(BOOL)env;

/** 设置sdk audio 代理对象 */
- (void)setSdkAudioDelegate:(nullable id<ZGSdkAudioDelegate>)delegate;

/** 设置sdk video 代理对象 */
- (void)setSdkVideoDelegate:(nullable id<ZGSdkVideoDelegate>)delegate;

/** 设置sdk 通用代理对象 */
- (void)setSdkCommonDelegate:(nullable id<ZGSdkCommonDelegate>)delegate;

/** 拉流之前 */
- (void)beforePlayingStream:(nonnull NSString *)streamId;

/** 拉流之后  */
- (void)afterPlayingStream:(nonnull NSString *)streamId;

/** 推流之前 */
- (void)beforePublishStream:(nonnull NSString *)streamId;

/** 推流之后 */
- (void)afterPublishStream:(nonnull NSString *)streamId;

/** 是否启用自动配置 */
- (BOOL)isEnableAutoConfig;

/** 开启或关闭自动配置 */
- (void)enableAutoConfig:(BOOL)enable;

/**
 *------------------ 获取参数 -----------------
 * 获取appid
 */
- (int64_t)getAppid:(ZGAppidVersion)version;

/** 获取appkey */
- (nonnull NSData *)getAppkey:(ZGAppidVersion)version;

/** 获取标题 */
- (nonnull NSString *)getTitle;

@end
