// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>

/** app类型 */
typedef NS_ENUM(NSInteger, ZGAppType)
{
    /** 实时视频 */
    ZGAppTypeVideoTalk,
    /** 实时语音 */
    ZGAppTypeAudioLive,
    /** 在线直播 */
    ZGAppTypeLiveDemo5,
};
