// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>

/** appid版本 */
typedef NS_ENUM(NSInteger, ZGAppidVersion)
{
    /** 国内版 */
    ZGAppidVersionUDP,
    /** 国际版 */
    ZGAppidVersionINTERNATIONAL,
    /** rtmp版 */
    ZGAppidVersionRTMP,
    /** 自定义版 */
    ZGAppidVersionCUSTOM,
};
