// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import "ZGConfigResult.h"
#import <Foundation/Foundation.h>


/** 自动配置代理 */
@protocol ZGAutoConfigDelegate

/** 更新配置完成 */
- (void)onUpdateConfigComplete:(ZGConfigResult)result;

/** initsdk完成 */
- (void)onInitSdk:(int32_t)errorCode;

@end
