// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import "ZGStringRequest.h"
#import <Foundation/Foundation.h>
@class ZGResponseListener;


/** http请求 */
@protocol ZGHttpClient

/** add request queue */
- (int32_t)addRequestQueue:(nonnull ZGStringRequest *)request
                 requestId:(int32_t)requestId
                  listener:(nullable ZGResponseListener *)listener;

/** remove request all */
- (void)removeRequestAll;

/** 移除指定id请求 */
- (void)removeRequest:(int32_t)requestId;

@end
