// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>
@protocol ZGHttpClient;


@protocol ZGHttpClientFactory

- (nullable id<ZGHttpClient>)createHttpClient;

@end
