// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>

/** 请求方法 */
typedef NS_ENUM(NSInteger, ZGRequestMethod)
{
    /** post */
    ZGRequestMethodPOST,
    /** get */
    ZGRequestMethodGET,
};
