// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import "ZGStreamInfo.h"
#import <Foundation/Foundation.h>

@interface ZGRoomInfo : NSObject
- (nonnull instancetype)initWithRoomId:(nonnull NSString *)roomId
                              roomName:(nonnull NSString *)roomName
                          anchorIdName:(nonnull NSString *)anchorIdName
                        anchorNickName:(nonnull NSString *)anchorNickName
                            streamInfo:(nonnull NSArray<ZGStreamInfo *> *)streamInfo;
+ (nonnull instancetype)roomInfoWithRoomId:(nonnull NSString *)roomId
                                  roomName:(nonnull NSString *)roomName
                              anchorIdName:(nonnull NSString *)anchorIdName
                            anchorNickName:(nonnull NSString *)anchorNickName
                                streamInfo:(nonnull NSArray<ZGStreamInfo *> *)streamInfo;

@property (nonatomic, readonly, nonnull) NSString * roomId;

@property (nonatomic, readonly, nonnull) NSString * roomName;

@property (nonatomic, readonly, nonnull) NSString * anchorIdName;

@property (nonatomic, readonly, nonnull) NSString * anchorNickName;

@property (nonatomic, readonly, nonnull) NSArray<ZGStreamInfo *> * streamInfo;

@end
