// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>

@interface ZGStreamInfo : NSObject
- (nonnull instancetype)initWithStreamId:(nonnull NSString *)streamId;
+ (nonnull instancetype)streamInfoWithStreamId:(nonnull NSString *)streamId;

@property (nonatomic, readonly, nonnull) NSString * streamId;

@end
