// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>
@protocol ZGSystemToolkit;


/** 系统工具包工厂 */
@protocol ZGSystemToolkitFactory

- (nullable id<ZGSystemToolkit>)createSystemToolkit;

@end
