// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>


/** 系统工具包 */
@protocol ZGSystemToolkit

/** 获取签名 传 签名类型 : "SHA256", "SHA128" */
- (nonnull NSArray<NSString *> *)getSignature:(nonnull NSString *)signatureType;

@end
