// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>

/** app状态 */
typedef NS_ENUM(NSInteger, ZGAppState)
{
    /** 初始化sdk */
    ZGAppStateInitSdk,
    /** 初始化sdk前 */
    ZGAppStateBeforeInitSdk,
    /** 初始化sdk后 */
    ZGAppStateAfterInitSdk,
    /** app推流前  */
    ZGAppStateBeforePublishStream,
    /** app推流后 */
    ZGAppStateAfterPublishStream,
    /** app拉流前 */
    ZGAppStateBeforePlayingStream,
    /** app拉流后 */
    ZGAppStateAfterPlayingStream,
};
