// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>

/** config_result */
typedef NS_ENUM(NSInteger, ZGConfigResult)
{
    /** 加载失败 */
    ZGConfigResultLoadFailure,
    /** 加载配置成功 */
    ZGConfigResultLoadSuccess,
};
