// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>
@protocol ZGDataStorageUtil;


/** 数据存储工厂 */
@protocol ZGDataStorageFactory

- (nullable id<ZGDataStorageUtil>)createDataStorage;

@end
