// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>


/** 数据存储 */
@protocol ZGDataStorageUtil

/** 保存参数 */
- (int32_t)saveParam:(nonnull NSString *)key
               value:(nonnull NSString *)value;

/** 获取参数 */
- (nonnull NSString *)getParam:(nonnull NSString *)key
                  defaultValue:(nonnull NSString *)defaultValue;

@end
