// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>


@interface ZGInitSdkCompletionCallback : NSObject

- (void)onInitSdk:(int32_t)errorCode;

@end
