// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>
@class ZGInitSdkCompletionCallback;


@protocol ZGSdkCommonDelegate

/** 初始化sdk */
- (void)onInitSdk:(int64_t)appId
           appKey:(nonnull NSData *)appKey
         callback:(nullable ZGInitSdkCompletionCallback *)callback;

/** 设置业务类型 */
- (void)onSetBusinessType:(int32_t)businessType;

/** 测试环境 */
- (void)onSetTestEnv:(BOOL)env;

/** 设置延迟模式 */
- (void)onSetLatencyMode:(int32_t)mode;

/** 设置引擎配置 */
- (void)onSetConfig:(nonnull NSString *)config;

/** 设置流控 */
- (void)onSetTrafficControl:(int32_t)trafficControl
                     enable:(BOOL)enable;

/** 设置自定义转推 */
- (void)onSetPublishConfig:(nonnull NSString *)config
              channelIndex:(int32_t)channelIndex;

@end
