// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>


@protocol ZGSdkVideoDelegate

/** 硬件解码 */
- (void)onHardwareDecode:(BOOL)hardwareDecode;

/** 硬件编码 */
- (void)onHardwareEncode:(BOOL)hardwareEncode;

/** 设置视频编码分辨率 */
- (void)onSetVideoEncodeResolution:(int32_t)width
                            height:(int32_t)height;

/** 设置视频采集分辨率 */
- (void)onSetVideoCaptureResolution:(int32_t)width
                             height:(int32_t)height;

/** 设置视频帧率 */
- (void)onSetVideoFps:(int32_t)fps;

/** 设置视频码率 */
- (void)onSetVideoBitrate:(int32_t)bitrate;

/** 分层编码 */
- (void)onSetVideoCodeid:(int32_t)codeid
            channelIndex:(int32_t)channelIndex;

/** 设置前摄像 */
- (void)onFrontCam:(BOOL)cam
      channelIndex:(int32_t)channelIndex;

/** 设置编码器码率控制策略 */
- (void)onSetVideoEncoderRateControlConfig:(int32_t)strategy
                                encoderCrf:(int32_t)encoderCrf
                              channelIndex:(int32_t)channelIndex;

/** 拉指定分辨率层 */
- (void)onActivateVedioPlayStream:(nonnull NSString *)streamId
                           active:(BOOL)active
                       videoLayer:(int32_t)videoLayer;

@end
