// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import "ZGRequestMethod.h"
#import <Foundation/Foundation.h>

@interface ZGStringRequest : NSObject
- (nonnull instancetype)initWithUrl:(nonnull NSString *)url
                             params:(nonnull NSDictionary<NSString *, NSString *> *)params
                             method:(ZGRequestMethod)method
                          timeoutMs:(int32_t)timeoutMs;
+ (nonnull instancetype)stringRequestWithUrl:(nonnull NSString *)url
                                      params:(nonnull NSDictionary<NSString *, NSString *> *)params
                                      method:(ZGRequestMethod)method
                                   timeoutMs:(int32_t)timeoutMs;

@property (nonatomic, readonly, nonnull) NSString * url;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSString *> * params;

@property (nonatomic, readonly) ZGRequestMethod method;

@property (nonatomic, readonly) int32_t timeoutMs;

@end
