// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#import <Foundation/Foundation.h>
@class ZGUtilsManager;
@protocol ZGDataStorageFactory;
@protocol ZGHttpClientFactory;
@protocol ZGSystemToolkitFactory;


@interface ZGUtilsManager : NSObject

+ (nullable ZGUtilsManager *)sharedInstance;

- (void)setHttpClientFactory:(nullable id<ZGHttpClientFactory>)f;

- (void)setDataStorageFactory:(nullable id<ZGDataStorageFactory>)f;

- (void)setSystemToolkitFactory:(nullable id<ZGSystemToolkitFactory>)f;

@end
