// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <functional>

namespace zego {

enum class AppState : int {
    /** 初始化sdk */
    INIT_SDK,
    /** 初始化sdk前 */
    BEFORE_INIT_SDK,
    /** 初始化sdk后 */
    AFTER_INIT_SDK,
    /** app推流前  */
    BEFORE_PUBLISH_STREAM,
    /** app推流后 */
    AFTER_PUBLISH_STREAM,
    /** app拉流前 */
    BEFORE_PLAYING_STREAM,
    /** app拉流后 */
    AFTER_PLAYING_STREAM,
};

}  // namespace zego

namespace std {

template <>
struct hash<::zego::AppState> {
    size_t operator()(::zego::AppState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
