// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <functional>

namespace zego {

enum class AppidVersion : int {
    /** 国内版 */
    UDP,
    /** 国际版 */
    INTERNATIONAL,
    /** rtmp版 */
    RTMP,
    /** 自定义版 */
    CUSTOM,
};

}  // namespace zego

namespace std {

template <>
struct hash<::zego::AppidVersion> {
    size_t operator()(::zego::AppidVersion type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
