// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>

namespace zego {

enum class ConfigResult;

/** 自动配置代理 */
class AutoConfigDelegate {
public:
    virtual ~AutoConfigDelegate() {}

    /** 更新配置完成 */
    virtual void on_update_config_complete(ConfigResult result) = 0;

    /** initsdk完成 */
    virtual void on_init_sdk(int32_t error_code) = 0;
};

}  // namespace zego
