// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace zego {

class AutoConfigDelegate;
class RoomListUpdateListener;
class SdkAudioDelegate;
class SdkCommonDelegate;
class SdkVideoDelegate;
enum class AppType;
enum class AppidVersion;

/** 配置api */
class ConfigApi {
public:
    virtual ~ConfigApi() {}

    /** 创建配置api */
    static std::shared_ptr<ConfigApi> create();

    /** 设置自动配置参数 */
    virtual void set_auto_config_params(AppType type, const std::string & config_id) = 0;

    /** 更新配置 */
    virtual void update_app_config(const std::shared_ptr<AutoConfigDelegate> & delegate) = 0;

    /** 设置房间列表监听 */
    virtual void set_room_list_update_listener(const std::shared_ptr<RoomListUpdateListener> & listener) = 0;

    /** 更新房间列表 */
    virtual void update_room_list(int64_t appid) = 0;

    /** 设置sdk audio 代理对象 */
    virtual void set_sdk_audio_delegate(const std::shared_ptr<SdkAudioDelegate> & delegate) = 0;

    /** 设置sdk video 代理对象 */
    virtual void set_sdk_video_delegate(const std::shared_ptr<SdkVideoDelegate> & delegate) = 0;

    /** 设置sdk 通用代理对象 */
    virtual void set_sdk_common_delegate(const std::shared_ptr<SdkCommonDelegate> & delegate) = 0;

    /** 拉流之前 */
    virtual void before_playing_stream(const std::string & stream_id) = 0;

    /** 拉流之后  */
    virtual void after_playing_stream(const std::string & stream_id) = 0;

    /** 推流之前 */
    virtual void before_publish_stream(const std::string & stream_id) = 0;

    /** 推流之后 */
    virtual void after_publish_stream(const std::string & stream_id) = 0;

    /** 是否启用自动配置 */
    virtual bool is_enable_auto_config() = 0;

    /** 开启或关闭自动配置 */
    virtual void enable_auto_config(bool enable) = 0;

    /**
     *------------------ 获取参数 -----------------
     * 获取appid
     */
    virtual int64_t get_appid(AppidVersion version) = 0;

    /** 获取appkey */
    virtual std::vector<uint8_t> get_appkey(AppidVersion version) = 0;

    /** 获取标题 */
    virtual std::string get_title() = 0;
};

}  // namespace zego
