// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>
#include <string>

namespace zego {

/** 数据存储 */
class DataStorageUtil {
public:
    virtual ~DataStorageUtil() {}

    /** 保存参数 */
    virtual int32_t save_param(const std::string & key, const std::string & value) = 0;

    /** 获取参数 */
    virtual std::string get_param(const std::string & key, const std::string & default_value) = 0;
};

}  // namespace zego
