// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <memory>

namespace zego {

class DataStorageUtil;

/** 数据存储工厂 */
class DataStorageFactory {
public:
    virtual ~DataStorageFactory() {}

    virtual std::shared_ptr<DataStorageUtil> create_data_storage() = 0;
};

}  // namespace zego
