// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace zego {

class ResponseListener;
struct StringRequest;

/** http请求 */
class HttpClient {
public:
    virtual ~HttpClient() {}

    /** add request queue */
    virtual int32_t add_request_queue(const StringRequest & request, int32_t request_id, const std::shared_ptr<ResponseListener> & listener) = 0;

    /** remove request all */
    virtual void remove_request_all() = 0;

    /** 移除指定id请求 */
    virtual void remove_request(int32_t request_id) = 0;
};

}  // namespace zego
