// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <memory>

namespace zego {

class HttpClient;

class HttpClientFactory {
public:
    virtual ~HttpClientFactory() {}

    virtual std::shared_ptr<HttpClient> create_http_client() = 0;
};

}  // namespace zego
