// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>
#include <string>

namespace zego {

class ResponseListener {
public:
    virtual ~ResponseListener() {}

    virtual void on_response(const std::string & response, int32_t request_id) = 0;

    virtual void on_error_response(const std::string & error, int32_t state_code, int32_t request_id) = 0;
};

}  // namespace zego
