// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <vector>

namespace zego {

struct RoomInfo;

class RoomListUpdateListener {
public:
    virtual ~RoomListUpdateListener() {}

    virtual void on_update_room_list(const std::vector<RoomInfo> & room_list) = 0;

    virtual void on_update_room_list_error() = 0;
};

}  // namespace zego
