// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace zego {

class InitSdkCompletionCallback;

class SdkCommonDelegate {
public:
    virtual ~SdkCommonDelegate() {}

    /** 初始化sdk */
    virtual void on_init_sdk(int64_t app_id, const std::vector<uint8_t> & app_key, const std::shared_ptr<InitSdkCompletionCallback> & callback) = 0;

    /** 设置业务类型 */
    virtual void on_set_business_type(int32_t business_type) = 0;

    /** 测试环境 */
    virtual void on_set_test_env(bool env) = 0;

    /** 设置延迟模式 */
    virtual void on_set_latency_mode(int32_t mode) = 0;

    /** 设置引擎配置 */
    virtual void on_set_config(const std::string & config) = 0;

    /** 设置流控 */
    virtual void on_set_trafficControl(int32_t traffic_control, bool enable) = 0;

    /** 设置自定义转推 */
    virtual void on_set_publish_config(const std::string & config, int32_t channel_index) = 0;
};

}  // namespace zego
