// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>

namespace zego {

class SdkAudioDelegate {
public:
    virtual ~SdkAudioDelegate() {}

    /** 设置音频码率 */
    virtual void on_set_audio_bitrate(int32_t bitrate) = 0;

    /** 设置音频模式 */
    virtual void on_set_audio_device_mode(int32_t mode) = 0;

    /** 回声消除开关 */
    virtual void on_enable_aec(bool enable) = 0;

    /** 耳机插入状态下是否使用回声消除 */
    virtual void on_enable_aecwhen_headset_detected(bool enable) = 0;

    /** 是否开启离散音频包发送 */
    virtual void on_enable_dtx(bool enable) = 0;

    /** 音频采集自动增益开关 */
    virtual void on_enable_agc(bool enable) = 0;

    /** 设置音频通道数 */
    virtual void on_set_audio_channel_count(int32_t channel_count) = 0;
};

}  // namespace zego
