// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <cstdint>
#include <string>

namespace zego {

class SdkVideoDelegate {
public:
    virtual ~SdkVideoDelegate() {}

    /** 硬件解码 */
    virtual void on_hardware_decode(bool hardware_decode) = 0;

    /** 硬件编码 */
    virtual void on_hardware_encode(bool hardware_encode) = 0;

    /** 设置视频编码分辨率 */
    virtual void on_set_video_encode_resolution(int32_t width, int32_t height) = 0;

    /** 设置视频采集分辨率 */
    virtual void on_set_video_capture_resolution(int32_t width, int32_t height) = 0;

    /** 设置视频帧率 */
    virtual void on_set_video_fps(int32_t fps) = 0;

    /** 设置视频码率 */
    virtual void on_set_video_bitrate(int32_t bitrate) = 0;

    /** 分层编码 */
    virtual void on_set_video_codeid(int32_t codeid, int32_t channel_index) = 0;

    /** 设置前摄像 */
    virtual void on_front_cam(bool cam, int32_t channel_index) = 0;

    /** 设置编码器码率控制策略 */
    virtual void on_set_video_encoder_rate_control_config(int32_t strategy, int32_t encoder_crf, int32_t channel_index) = 0;

    /** 拉指定分辨率层 */
    virtual void on_activate_vedio_play_stream(const std::string & stream_id, bool active, int32_t video_layer) = 0;
};

}  // namespace zego
