// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <string>
#include <utility>

namespace zego {

struct StreamInfo final {
    std::string stream_id;

    StreamInfo(std::string stream_id_)
    : stream_id(std::move(stream_id_))
    {}
};

}  // namespace zego
