// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include "request_method.hpp"
#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>

namespace zego {

struct StringRequest final {
    std::string url;
    std::unordered_map<std::string, std::string> params;
    RequestMethod method;
    int32_t timeout_ms;

    StringRequest(std::string url_,
                  std::unordered_map<std::string, std::string> params_,
                  RequestMethod method_,
                  int32_t timeout_ms_)
    : url(std::move(url_))
    , params(std::move(params_))
    , method(std::move(method_))
    , timeout_ms(std::move(timeout_ms_))
    {}
};

}  // namespace zego
