// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <memory>

namespace zego {

class SystemToolkit;

/** 系统工具包工厂 */
class SystemToolkitFactory {
public:
    virtual ~SystemToolkitFactory() {}

    virtual std::shared_ptr<SystemToolkit> create_system_toolkit() = 0;
};

}  // namespace zego
