// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <string>
#include <vector>

namespace zego {

/** 系统工具包 */
class SystemToolkit {
public:
    virtual ~SystemToolkit() {}

    /** 获取签名 传 签名类型 : "SHA256", "SHA128" */
    virtual std::vector<std::string> get_signature(const std::string & signature_type) = 0;
};

}  // namespace zego
