// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from auto_config.djinni

#pragma once

#include <memory>

namespace zego {

class DataStorageFactory;
class HttpClientFactory;
class SystemToolkitFactory;

class UtilsManager {
public:
    virtual ~UtilsManager() {}

    static std::shared_ptr<UtilsManager> sharedInstance();

    virtual void set_http_client_factory(const std::shared_ptr<HttpClientFactory> & f) = 0;

    virtual void set_data_storage_factory(const std::shared_ptr<DataStorageFactory> & f) = 0;

    virtual void set_system_toolkit_factory(const std::shared_ptr<SystemToolkitFactory> & f) = 0;
};

}  // namespace zego
